pipeline {
    agent {
        node {
            label 'LINUX1'
        }
    }

     options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

     parameters {
        choice(
            name: 'ACTION',
            choices: ['apply', 'destroy'],
            description: 'Select whether to apply or destroy the infrastructure'
        )
    }

    stages {
        stage('Init') {
            steps {
               script {
                withAWS(region:'us-east-1', credentials:'aws-creds') {
                     sh """
                     cd 00-vpc
                     terraform init
                     """
                }
               }
            }
        }

        stage('Plan') {
            when {
                expression {
                    params.action == 'apply'
                }
            }

            steps {
                script {
                withAWS(region:'us-east-1', credentials:'aws-creds') {
                     sh """
                     cd 00-vpc
                     terraform plan
                     """
                }
               }
            }
        }

        stage('Apply') {
            when {
                expression {
                    params.action == 'apply'
                }
            }
            steps {
               script {
                withAWS(region:'us-east-1', credentials:'aws-creds') {
                     sh """
                     cd 00-vpc
                     terraform apply -auto-approve
                     """
                }
               }
            }
        }

         stage('Destroy') {
            when {
                expression {
                    params.action == 'destroy'
                }
            }
            steps {
               script {
                withAWS(region:'us-east-1', credentials:'aws-creds') {
                     sh """
                     cd 00-vpc
                     terraform destroy -auto-approve
                     """
                }
               }
            }
        }

        stage('Trigger SG') {
            steps {
                script {
                    build job: '10-sg',
                        wait: false,
                        propagate: false 
                }
            }
        }
    }

    post{
        always{
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}