pipeline {
    agent {
        node {
            label 'LINUX1'
        }
    }

     options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {
        stage('Init') {
            steps {
               script {
                withAWS(region:'us-east-1', credentials:'aws-creds') {
                     sh """
                     cd 30-bastion
                     terraform init
                     """
                }
               }
            }
        }

        stage('Plan') {
            steps {
                script {
                withAWS(region:'us-east-1', credentials:'aws-creds') {
                     sh """
                     cd 30-bastion
                     terraform plan
                     """
                }
               }
            }
        }

        stage('Apply') {
            steps {
               script {
                withAWS(region:'us-east-1', credentials:'aws-creds') {
                     sh """
                     cd 30-bastion
                     terraform apply -auto-approve
                     """
                }
               }
            }
        }

        stage('Destroy') {
            steps {
               script {
                withAWS(region:'us-east-1', credentials:'aws-creds') {
                     sh """
                     cd 30-bastion
                     terraform destroy -auto-approve
                     """
                }
               }
            }
        }
    }

    post{
        always{
            echo 'I will always say Hello again!'
            cleanWs()
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}